---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1
  - name: centos-6.7
  - name: centos-5.11

suites:
  - name: default
    run_list:
      - recipe[yum-jenkins::default]
